//package javaapplication1;
import java.awt.Color;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
//package my.mainframe;

/**
 * 
 * @author User
 */
public class MainFrameUI extends javax.swing.JFrame {

	/**
	 * Creates new form MainFrameUI
	 */
	public MainFrameUI() {
		initComponents();

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		//initialise buttons/labels
		DifficultyButtonGroup = new javax.swing.ButtonGroup();
		jLabel1 = new javax.swing.JLabel();
		newGameMain = new javax.swing.JButton();
		Instructions = new javax.swing.JButton();
		Quit = new javax.swing.JButton();
		EasyRadioButton = new javax.swing.JRadioButton("Easy", true);
		MediumRadioButton = new javax.swing.JRadioButton();
		HardRadioButton = new javax.swing.JRadioButton();
		customGameButton = new javax.swing.JButton();
		difficulty = SudokuGenerator.EASY;
		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		//set title label text, alignment
		jLabel1.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel1.setText("Sudoku");

		//set new game button text, add action
		newGameMain.setText("New Game");
		newGameMain.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				newGameMainActionPerformed(evt);
			}
		});

		//add instructions button text, add action
		Instructions.setText("Instructions");
		Instructions.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				InstructionsActionPerformed(evt);
			}
		});
		
		//add quit button text, action
		Quit.setText("Quit");
		Quit.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				QuitActionPerformed(evt);
			}
		});
		//add easy radio button to group
		DifficultyButtonGroup.add(EasyRadioButton);
		EasyRadioButton.setText("Easy");
		EasyRadioButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		EasyRadioButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				EasyRadioButtonActionPerformed(evt);
			}
		});
		//add medium radio button to group
		DifficultyButtonGroup.add(MediumRadioButton);
		MediumRadioButton.setText("Medium");
		MediumRadioButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		MediumRadioButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				MediumRadioButtonActionPerformed(evt);
			}
		});
		//add hard radio button to group
		DifficultyButtonGroup.add(HardRadioButton);
		HardRadioButton.setText("Hard");
		HardRadioButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		HardRadioButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				HardRadioButtonActionPerformed(evt);
			}
		});
		//set custom game text, add action
		customGameButton.setText("Custom Game");
		customGameButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				customGameButtonActionPerformed(evt);
			}
		});
		//add all components together
		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(63, 63, 63)
								.addComponent(EasyRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING,
																				false)
																				.addComponent(
																						MediumRadioButton,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						100, Short.MAX_VALUE)
																				.addComponent(
																						jLabel1,
																						javax.swing.GroupLayout.Alignment.LEADING,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(HardRadioButton,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 85,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING, false)
																.addComponent(newGameMain,
																		javax.swing.GroupLayout.Alignment.LEADING,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addComponent(Instructions,
																		javax.swing.GroupLayout.Alignment.LEADING,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addComponent(customGameButton,
																		javax.swing.GroupLayout.Alignment.LEADING,
																		javax.swing.GroupLayout.DEFAULT_SIZE, 110,
																		Short.MAX_VALUE))
												.addComponent(Quit, javax.swing.GroupLayout.PREFERRED_SIZE,
														110, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addContainerGap(65, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(48, 48, 48)
								.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18)
								.addComponent(newGameMain)
								.addGap(30, 30, 30)
								.addComponent(customGameButton)
								.addGap(29, 29, 29)
								.addComponent(Instructions)
								.addGap(30, 30, 30)
								.addGroup(
										layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(EasyRadioButton).addComponent(MediumRadioButton)
												.addComponent(HardRadioButton)).addGap(32, 32, 32)
								.addComponent(Quit).addContainerGap(63, Short.MAX_VALUE)));
		this.getContentPane().setBackground(Color.cyan);

		pack();
	}// </editor-fold>

	private void QuitActionPerformed(java.awt.event.ActionEvent evt) {
		System.exit(0);
	}
	//set new game button action
	private void newGameMainActionPerformed(java.awt.event.ActionEvent evt) {
		this.setVisible(false);
		new GameFrame().setVisible(true);
		SudokuBoard.getInstance().setDifficulty(difficulty);
		SudokuBoard.getInstance().newBoard();
	}
	//set instuctions button action
	private void InstructionsActionPerformed(java.awt.event.ActionEvent evt) {
		this.setVisible(false);
		new InstructionFrame().setVisible(true);
	}
	//set radio button actions
	private void MediumRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {
		difficulty = SudokuGenerator.MEDIUM;
	}

	private void EasyRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {
		difficulty = SudokuGenerator.MEDIUM;
	}

	private void HardRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {
		difficulty = SudokuGenerator.HARD;
	}
	//set custom game button actions
	private void customGameButtonActionPerformed(java.awt.event.ActionEvent evt) {
		this.setVisible(false);
		new CustomGameFrame().setVisible(true);
		// ---------------Clear the board-------------------
		SudokuBoard.getInstance().createCustomBoard();
	}

	/**
	 * @param args
	 *           the command line arguments
	 */
	public static void main(String args[]) {
		// Board.getInstance().clear();
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainFrameUI.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainFrameUI.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainFrameUI.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainFrameUI.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainFrameUI().setVisible(true);

			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.ButtonGroup DifficultyButtonGroup;
	private javax.swing.JRadioButton EasyRadioButton;
	private javax.swing.JRadioButton HardRadioButton;
	private javax.swing.JButton Instructions;
	private javax.swing.JRadioButton MediumRadioButton;
	private javax.swing.JButton Quit;
	private javax.swing.JButton customGameButton;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JButton newGameMain;
	private int difficulty;
	// End of variables declaration
}
